site_name: The Haskell Foundation Framework
site_description: The Haskell Foundation Framework
site_author: Foundation contributors
repo_url: https://github.com/haskell-foundation/foundation/tree/master/docs
copyright: Copyright (c) 2016-2017, Foundation contributors
docs_dir: docs
site_dir: _site
theme: readthedocs

pages:
- Introduction: index.md
- Home: home.md
- Changelog: CHANGELOG.md
- Core documentation:
  - Collection: core-collection.md
  - Numerical: core-numerical.md
- Advanced:
  - Runtime option: advanced-runtime.md
- Porting: porting.md
- Project documentation:
  - Contributors Guide: contributing.md
#  - Maintainer guide: MAINTAINER_GUIDE.md

markdown_extensions:
- toc:
    permalink: true
